function [terms,conc_1,conc_234]=compute_terms_3d(ne,conc_,chi,n1,n2,nex)

% === Compute terms =======================================================

terms=zeros(ne,6,3,3,3);

if isscalar(chi)
    parfor e=1:1:ne %Parfor must be feasible!!!
        terms(e,:,:,:,:)=compute_terms_in_sfsj_3d(e,conc_,chi,n1,n2);
    end
else
    parfor e=1:1:ne %Parfor must be feasible!!!
        terms(e,:,:,:,:)=compute_terms_in_sfsj_gradient_3d(e,conc_,chi,n1,n2,nex);
    end
end

% reduced_conc_=conc_(:,1,:,:,:);

% reduced_conc_=conc_;

conc_1=conc_(:,1,:,:,:);
conc_234=conc_(:,2:1:4,:,:,:);

end

% function elemental_terms=compute_terms_in_sfsj_gradient_3d(e,conc_,chi,n1,n2,nex)
% elemental_terms=zeros(6,3,3,3);
% 
% n1xth=mod(e,nex);
% if n1xth==0
%     n1xth=nex;
% end
% 
% for iz=1:1:3
%     for iy=1:1:3
%         for ix=1:1:3
%             
%             sub_term_1=...
%                 -1/(conc_(e,1,ix,iy,iz)^2*n1)...
%                 +1/((1-conc_(e,1,ix,iy,iz))^2*n2);
%             
% %             sub_term_1=...
% %                 -1/(conc_(e,1,ix,iy,iz)^2*n1)...
% %                 +1/((1-conc_(e,1,ix,iy,iz))^2*n2);
%             
%             sub_term_2=...
%                 conc_(e,2,ix,iy,iz)^2+...
%                 conc_(e,3,ix,iy,iz)^2+...
%                 conc_(e,4,ix,iy,iz)^2;
%             sub_term_3=...
%                 1/(conc_(e,1,ix,iy,iz)*n1)+...
%                 1/((1-conc_(e,1,ix,iy,iz))*n2)-...
%                 2*chi(n1xth,ix);
%             
%             sub_term_4=...
%                 conc_(e,5,ix,iy,iz)+...
%                 conc_(e,6,ix,iy,iz)+...
%                 conc_(e,7,ix,iy,iz);
%             
%             elemental_terms(1,ix,iy,iz)=...
%                 sub_term_1*sub_term_2;
%             elemental_terms(2,ix,iy,iz)=...
%                 sub_term_3*sub_term_4;
%             elemental_terms(3,ix,iy,iz)=...
%                 sub_term_4;
%             elemental_terms(4,ix,iy,iz)=...
%                 2*...
%                 ((conc_(e,1,ix,iy,iz)^3*n1)^-1+...
%                 ((1-conc_(e,1,ix,iy,iz))^3*n2)^-1)*...
%                 sub_term_2;
%             elemental_terms(5,ix,iy,iz)=...
%                 sub_term_1*...
%                 (2*(conc_(e,2,ix,iy,iz)+...
%                 conc_(e,3,ix,iy,iz)+...
%                 conc_(e,4,ix,iy,iz))+...
%                 sub_term_4);
%             
% %             elemental_terms(5,ix,iy,iz)=...
% %                 sub_term_1*...
% %                 (2*(conc_(e,2,ix,iy,iz)+...
% %                 conc_(e,3,ix,iy,iz)+...
% %                 conc_(e,4,ix,iy,iz))+...
% %                 sub_term_4);
%             
%             elemental_terms(6,ix,iy,iz)=...
%                 sub_term_3;
%             
%         end
%     end
% end
% end

function elemental_terms=compute_terms_in_sfsj_3d(e,conc_,chi,n1,n2)
elemental_terms=zeros(6,3,3,3);
for iz=1:1:3
    for iy=1:1:3
        for ix=1:1:3
            
            sub_term_1=...
                -1/(conc_(e,1,ix,iy,iz)^2*n1)...
                +1/((1-conc_(e,1,ix,iy,iz))^2*n2);
            sub_term_2=...
                conc_(e,2,ix,iy,iz)^2+...
                conc_(e,3,ix,iy,iz)^2+...
                conc_(e,4,ix,iy,iz)^2;
            sub_term_3=...
                1/(conc_(e,1,ix,iy,iz)*n1)+...
                1/((1-conc_(e,1,ix,iy,iz))*n2)-...
                2*chi;
            sub_term_4=...
                conc_(e,5,ix,iy,iz)+...
                conc_(e,6,ix,iy,iz)+...
                conc_(e,7,ix,iy,iz);
            
            elemental_terms(1,ix,iy,iz)=...
                sub_term_1*sub_term_2;
            elemental_terms(2,ix,iy,iz)=...
                sub_term_3*sub_term_4;
            elemental_terms(3,ix,iy,iz)=...
                sub_term_4;
            elemental_terms(4,ix,iy,iz)=...
                2*...
                ((conc_(e,1,ix,iy,iz)^3*n1)^-1+...
                ((1-conc_(e,1,ix,iy,iz))^3*n2)^-1)*...
                sub_term_2;
            
            
            
            %----------------------------------------------
%             elemental_terms(5,ix,iy,iz)=...
%                 sub_term_1*...
%                 (2*(conc_(e,2,ix,iy,iz)+...
%                 conc_(e,3,ix,iy,iz)+...
%                 conc_(e,4,ix,iy,iz))+...
%                 sub_term_4);
            
            
            elemental_terms(5,ix,iy,iz)=...
                sub_term_1;
            
            %----------------------------------------------
            elemental_terms(6,ix,iy,iz)=...
                sub_term_3;
            
        end
    end
end
end