function sj=compute_sj_with_precomputed_terms_and_sj_properties_3d(...
    nnz_,dt,weights,dxyz,diffT,wTerms,terms,sj_properties)

% This method has been abandoned. sj_properties is a large matrix.
% It takes up too much time just to pass the arguments to child functions

sj=zeros(1,nnz_);

w=[5/18 4/9 5/18];

if isscalar(diffT)
    parfor sjth=1:1:nnz_
        sj(sjth)=compute_sjth_sj_with_terms_and_sj_properties_3d(sjth,...
            w,dt,diffT,weights,dxyz,wTerms,terms,sj_properties);
    end
else
    parfor sjth=1:1:nnz_
        sj(sjth)=...
            compute_sjth_sj_gradient_with_terms_and_sj_properties_3d(...
            sjth,w,dt,diffT,weights,dxyz,wTerms,terms,sj_properties);
    end
end

end

% === Temperature gradient is present =============================================

function solution=compute_sjth_sj_gradient_with_terms_and_sj_properties_3d(...
    sjth,w,dt,diffT,weights,dxyz,wTerms,terms,sj_properties)
% disp('hefda')
solution=0;
for i_positional_element=1:1:8
    if sj_properties(sjth,i_positional_element,1)~=0
        for ix=1:1:3
            for iy=1:1:3
                for iz=1:1:3
                    
                    solution=solution+w(ix)*w(iy)*w(iz)*(...
                        weights(sj_properties(sjth,i_positional_element,2),sj_properties(sjth,i_positional_element,4),1,ix,iy,iz)*weights(sj_properties(sjth,i_positional_element,3),sj_properties(sjth,i_positional_element,5),1,ix,iy,iz)/dt...
                        -diffT(sj_properties(sjth,i_positional_element,6),ix)*weights(sj_properties(sjth,i_positional_element,2),sj_properties(sjth,i_positional_element,4),1,ix,iy,iz)...
                        *(weights(sj_properties(sjth,i_positional_element,3),sj_properties(sjth,i_positional_element,5),1,ix,iy,iz)...
                        *terms(sj_properties(sjth,i_positional_element,1),4,ix,iy,iz)...
                        +weights(sj_properties(sjth,i_positional_element,3),sj_properties(sjth,i_positional_element,5),1,ix,iy,iz)...
                        *terms(sj_properties(sjth,i_positional_element,1),5,ix,iy,iz)...
                        +terms(sj_properties(sjth,i_positional_element,1),6,ix,iy,iz)...
                        *wTerms(sj_properties(sjth,i_positional_element,3),sj_properties(sjth,i_positional_element,5),ix,iy,iz))...
                        +wTerms(sj_properties(sjth,i_positional_element,2),sj_properties(sjth,i_positional_element,4),ix,iy,iz)...
                        *wTerms(sj_properties(sjth,i_positional_element,3),sj_properties(sjth,i_positional_element,5),ix,iy,iz)...
                        ...
                        );
                end
            end
        end
    end
end
solution=solution*dxyz;
end

% === No temperature gradient =============================================

function solution=compute_sjth_sj_with_terms_and_sj_properties_3d(...
    sjth,w,dt,diffT,weights,dxyz,wTerms,terms,sj_properties)

solution=0;
for i_positional_element=1:1:8
    if sj_properties(sjth,i_positional_element,1)~=0
        for ix=1:1:3
            for iy=1:1:3
                for iz=1:1:3
                    
                    solution=solution+w(ix)*w(iy)*w(iz)*(...
                        weights(sj_properties(sjth,i_positional_element,2),sj_properties(sjth,i_positional_element,4),1,ix,iy,iz)*weights(sj_properties(sjth,i_positional_element,3),sj_properties(sjth,i_positional_element,5),1,ix,iy,iz)/dt...
                        -diffT*weights(sj_properties(sjth,i_positional_element,2),sj_properties(sjth,i_positional_element,4),1,ix,iy,iz)...
                        *(weights(sj_properties(sjth,i_positional_element,3),sj_properties(sjth,i_positional_element,5),1,ix,iy,iz)...
                        *terms(sj_properties(sjth,i_positional_element,1),4,ix,iy,iz)...
                        +weights(sj_properties(sjth,i_positional_element,3),sj_properties(sjth,i_positional_element,5),1,ix,iy,iz)...
                        *terms(sj_properties(sjth,i_positional_element,1),5,ix,iy,iz)...
                        +terms(sj_properties(sjth,i_positional_element,1),6,ix,iy,iz)...
                        *wTerms(sj_properties(sjth,i_positional_element,3),sj_properties(sjth,i_positional_element,5),ix,iy,iz))...
                        +wTerms(sj_properties(sjth,i_positional_element,2),sj_properties(sjth,i_positional_element,4),ix,iy,iz)...
                        *wTerms(sj_properties(sjth,i_positional_element,3),sj_properties(sjth,i_positional_element,5),ix,iy,iz)...
                        ...
                        );
                    
                end
            end
        end
    end
end
solution=solution*dxyz;
end