function sol=compute_specific_c_3d(nodal_vals,alpha,beta,gamma,eX,eY,eZ,coeffs)

sol=zeros(7,1);
first_index=-4;

x_alpha=map_to_global_1_compt_3d(alpha,beta,gamma,eX,[1 0 0]);
x_beta=map_to_global_1_compt_3d(alpha,beta,gamma,eX,[0 1 0]);
x_gamma=map_to_global_1_compt_3d(alpha,beta,gamma,eX,[0 0 1]);
x_alpha_beta=map_to_global_1_compt_3d(alpha,beta,gamma,eX,[1 1 0]);
x_alpha_gamma=map_to_global_1_compt_3d(alpha,beta,gamma,eX,[1 0 1]);
x_beta_gamma=map_to_global_1_compt_3d(alpha,beta,gamma,eX,[0 1 1]);
x_alpha_beta_gamma=map_to_global_1_compt_3d(alpha,beta,gamma,eX,[1 1 1]);

y_alpha=map_to_global_1_compt_3d(alpha,beta,gamma,eY,[1 0 0]);
y_beta=map_to_global_1_compt_3d(alpha,beta,gamma,eY,[0 1 0]);
y_gamma=map_to_global_1_compt_3d(alpha,beta,gamma,eY,[0 0 1]);
y_alpha_beta=map_to_global_1_compt_3d(alpha,beta,gamma,eY,[1 1 0]);
y_alpha_gamma=map_to_global_1_compt_3d(alpha,beta,gamma,eY,[1 0 1]);
y_beta_gamma=map_to_global_1_compt_3d(alpha,beta,gamma,eY,[0 1 1]);
y_alpha_beta_gamma=map_to_global_1_compt_3d(alpha,beta,gamma,eY,[1 1 1]);

z_alpha=map_to_global_1_compt_3d(alpha,beta,gamma,eZ,[1 0 0]);
z_beta=map_to_global_1_compt_3d(alpha,beta,gamma,eZ,[0 1 0]);
z_gamma=map_to_global_1_compt_3d(alpha,beta,gamma,eZ,[0 0 1]);
z_alpha_beta=map_to_global_1_compt_3d(alpha,beta,gamma,eZ,[1 1 0]);
z_alpha_gamma=map_to_global_1_compt_3d(alpha,beta,gamma,eZ,[1 0 1]);
z_beta_gamma=map_to_global_1_compt_3d(alpha,beta,gamma,eZ,[0 1 1]);
z_alpha_beta_gamma=map_to_global_1_compt_3d(alpha,beta,gamma,eZ,[1 1 1]);

derivative_local=zeros(9,1);

for orientation=1:1:8
    first_index=first_index+4;
    
    %---------These can be pre-computed-----------------------
    
    phi000=compute_weight_specific(alpha,beta,gamma,orientation,1,1,coeffs);
    phi000_alpha=compute_weight_specific(alpha,beta,gamma,orientation,1,2,coeffs);
    phi000_beta=compute_weight_specific(alpha,beta,gamma,orientation,1,3,coeffs);
    phi000_gamma=compute_weight_specific(alpha,beta,gamma,orientation,1,4,coeffs);
    phi000_alpha_alpha=compute_weight_specific(alpha,beta,gamma,orientation,1,5,coeffs);
    phi000_beta_beta=compute_weight_specific(alpha,beta,gamma,orientation,1,6,coeffs);
    phi000_gamma_gamma=compute_weight_specific(alpha,beta,gamma,orientation,1,7,coeffs);
    phi000_alpha_beta=compute_weight_specific(alpha,beta,gamma,orientation,1,8,coeffs);
    phi000_alpha_gamma=compute_weight_specific(alpha,beta,gamma,orientation,1,9,coeffs);
    phi000_beta_gamma=compute_weight_specific(alpha,beta,gamma,orientation,1,10,coeffs);
    
    phi100=compute_weight_specific(alpha,beta,gamma,orientation,2,1,coeffs);
    phi100_alpha=compute_weight_specific(alpha,beta,gamma,orientation,2,2,coeffs);
    phi100_beta=compute_weight_specific(alpha,beta,gamma,orientation,2,3,coeffs);
    phi100_gamma=compute_weight_specific(alpha,beta,gamma,orientation,2,4,coeffs);
    phi100_alpha_alpha=compute_weight_specific(alpha,beta,gamma,orientation,2,5,coeffs);
    phi100_beta_beta=compute_weight_specific(alpha,beta,gamma,orientation,2,6,coeffs);
    phi100_gamma_gamma=compute_weight_specific(alpha,beta,gamma,orientation,2,7,coeffs);
    phi100_alpha_beta=compute_weight_specific(alpha,beta,gamma,orientation,2,8,coeffs);
    phi100_alpha_gamma=compute_weight_specific(alpha,beta,gamma,orientation,2,9,coeffs);
    phi100_beta_gamma=compute_weight_specific(alpha,beta,gamma,orientation,2,10,coeffs);
    
    phi010=compute_weight_specific(alpha,beta,gamma,orientation,3,1,coeffs);
    phi010_alpha=compute_weight_specific(alpha,beta,gamma,orientation,3,2,coeffs);
    phi010_beta=compute_weight_specific(alpha,beta,gamma,orientation,3,3,coeffs);
    phi010_gamma=compute_weight_specific(alpha,beta,gamma,orientation,3,4,coeffs);
    phi010_alpha_alpha=compute_weight_specific(alpha,beta,gamma,orientation,3,5,coeffs);
    phi010_beta_beta=compute_weight_specific(alpha,beta,gamma,orientation,3,6,coeffs);
    phi010_gamma_gamma=compute_weight_specific(alpha,beta,gamma,orientation,3,7,coeffs);
    phi010_alpha_beta=compute_weight_specific(alpha,beta,gamma,orientation,3,8,coeffs);
    phi010_alpha_gamma=compute_weight_specific(alpha,beta,gamma,orientation,3,9,coeffs);
    phi010_beta_gamma=compute_weight_specific(alpha,beta,gamma,orientation,3,10,coeffs);
    
    phi001=compute_weight_specific(alpha,beta,gamma,orientation,4,1,coeffs);
    phi001_alpha=compute_weight_specific(alpha,beta,gamma,orientation,4,2,coeffs);
    phi001_beta=compute_weight_specific(alpha,beta,gamma,orientation,4,3,coeffs);
    phi001_gamma=compute_weight_specific(alpha,beta,gamma,orientation,4,4,coeffs);
    phi001_alpha_alpha=compute_weight_specific(alpha,beta,gamma,orientation,4,5,coeffs);
    phi001_beta_beta=compute_weight_specific(alpha,beta,gamma,orientation,4,6,coeffs);
    phi001_gamma_gamma=compute_weight_specific(alpha,beta,gamma,orientation,4,7,coeffs);
    phi001_alpha_beta=compute_weight_specific(alpha,beta,gamma,orientation,4,8,coeffs);
    phi001_alpha_gamma=compute_weight_specific(alpha,beta,gamma,orientation,4,9,coeffs);
    phi001_beta_gamma=compute_weight_specific(alpha,beta,gamma,orientation,4,10,coeffs);
    
    %-------------------------------------------------------------------
    
    sol(1)=sol(1)...
        +nodal_vals(first_index+1)*phi000...
        +nodal_vals(first_index+2)*(...
        phi100*x_alpha+phi010*x_beta+phi001*x_gamma)...
        +nodal_vals(first_index+3)*(...
        phi100*y_alpha+phi010*y_beta+phi001*y_gamma)...
        +nodal_vals(first_index+4)*(...
        phi100*z_alpha+phi010*z_beta+phi001*z_gamma...
        );
    
    derivative_local(1)=derivative_local(1)+...
        nodal_vals(first_index+1)*phi000_alpha...
        ...
        +nodal_vals(first_index+2)*(...
        phi100_alpha*x_alpha+phi010_alpha*x_beta...
        +phi010*x_alpha_beta+phi001_alpha*x_gamma...
        +phi001*x_alpha_gamma)...
        ...
        +nodal_vals(first_index+3)*(...
        phi100_alpha*y_alpha+phi010_alpha*y_beta...
        +phi010*y_alpha_beta+phi001_alpha*y_gamma...
        +phi001*y_alpha_gamma)...
        ...
        +nodal_vals(first_index+4)*(...
        phi100_alpha*z_alpha+phi010_alpha*z_beta...
        +phi010*z_alpha_beta+phi001_alpha*z_gamma...
        +phi001*z_alpha_gamma)...
        ...
        ;
    
    derivative_local(2)=derivative_local(2)+...
        nodal_vals(first_index+1)*phi000_beta...
        ...
        +nodal_vals(first_index+2)*(...
        phi100_beta*x_alpha+phi100*x_alpha_beta...
        +phi010_beta*x_beta+phi001_beta*x_gamma...
        +phi001*x_beta_gamma)...
        ...
        +nodal_vals(first_index+3)*(...
        phi100_beta*y_alpha+phi100*y_alpha_beta...
        +phi010_beta*y_beta+phi001_beta*y_gamma...
        +phi001*y_beta_gamma)...
        ...
        +nodal_vals(first_index+4)*(...
        phi100_beta*z_alpha+phi100*z_alpha_beta...
        +phi010_beta*z_beta+phi001_beta*z_gamma...
        +phi001*z_beta_gamma)...
        ;
    
    derivative_local(3)=derivative_local(3)+...
        nodal_vals(first_index+1)*phi000_gamma...
        ...
        +nodal_vals(first_index+2)*(...
        phi100_gamma*x_alpha+phi100*x_alpha_gamma...
        +phi010_gamma*x_beta+phi010*x_beta_gamma...
        +phi001_gamma*x_gamma)...
        ...
        +nodal_vals(first_index+3)*(...
        phi100_gamma*y_alpha+phi100*y_alpha_gamma...
        +phi010_gamma*y_beta+phi010*y_beta_gamma...
        +phi001_gamma*y_gamma)...
        ...
        +nodal_vals(first_index+4)*(...
        phi100_gamma*z_alpha+phi100*z_alpha_gamma...
        +phi010_gamma*z_beta+phi010*z_beta_gamma...
        +phi001_gamma*z_gamma)...
        ;
    
    derivative_local(4)=derivative_local(4)+...
        nodal_vals(first_index+1)*phi000_alpha_alpha...
        ...
        +nodal_vals(first_index+2)*(...
        phi100_alpha_alpha*x_alpha+phi010_alpha_alpha*x_beta...
        +phi010_alpha*x_alpha_beta+phi010_alpha*x_alpha_beta...
        +phi001_alpha_alpha*x_gamma+phi001_alpha*x_alpha_gamma...
        +phi001_alpha*x_alpha_gamma)...
        ...
        +nodal_vals(first_index+3)*(...
        phi100_alpha_alpha*y_alpha+phi010_alpha_alpha*y_beta...
        +phi010_alpha*y_alpha_beta+phi010_alpha*y_alpha_beta...
        +phi001_alpha_alpha*y_gamma+phi001_alpha*y_alpha_gamma...
        +phi001_alpha*y_alpha_gamma)...
        ...
        +nodal_vals(first_index+4)*(...
        phi100_alpha_alpha*z_alpha+phi010_alpha_alpha*z_beta...
        +phi010_alpha*z_alpha_beta+phi010_alpha*z_alpha_beta...
        +phi001_alpha_alpha*z_gamma+phi001_alpha*z_alpha_gamma...
        +phi001_alpha*z_alpha_gamma)...
        ;
    
    derivative_local(5)=derivative_local(5)+...
        nodal_vals(first_index+1)*phi000_beta_beta...
        ...
        +nodal_vals(first_index+2)*(...
        phi100_beta_beta*x_alpha+phi100_beta*x_alpha_beta...
        +phi100_beta*x_alpha_beta+phi010_beta_beta*x_beta...
        +phi001_beta_beta*x_gamma+phi001_beta*x_beta_gamma...
        +phi001_beta*x_beta_gamma)...
        ...
        +nodal_vals(first_index+3)*(...
        phi100_beta_beta*y_alpha+phi100_beta*y_alpha_beta...
        +phi100_beta*y_alpha_beta+phi010_beta_beta*y_beta...
        +phi001_beta_beta*y_gamma+phi001_beta*y_beta_gamma...
        +phi001_beta*y_beta_gamma)...
        ...
        +nodal_vals(first_index+4)*(...
        phi100_beta_beta*z_alpha+phi100_beta*z_alpha_beta...
        +phi100_beta*z_alpha_beta+phi010_beta_beta*z_beta...
        +phi001_beta_beta*z_gamma+phi001_beta*z_beta_gamma...
        +phi001_beta*z_beta_gamma)...
        ;
    
    derivative_local(6)=derivative_local(6)+...
        nodal_vals(first_index+1)*phi000_gamma_gamma...
        ...
        +nodal_vals(first_index+2)*(...
        phi100_gamma_gamma*x_alpha+phi100_gamma*x_alpha_gamma...
        +phi100_gamma*x_alpha_gamma+phi010_gamma_gamma*x_beta...
        +phi010_gamma*x_beta_gamma+phi010_gamma*x_beta_gamma...
        +phi001_gamma_gamma*x_gamma)...
        ...
        +nodal_vals(first_index+3)*(...
        phi100_gamma_gamma*y_alpha+phi100_gamma*y_alpha_gamma...
        +phi100_gamma*y_alpha_gamma+phi010_gamma_gamma*y_beta...
        +phi010_gamma*y_beta_gamma+phi010_gamma*y_beta_gamma...
        +phi001_gamma_gamma*y_gamma)...
        ...
        +nodal_vals(first_index+4)*(...
        phi100_gamma_gamma*z_alpha+phi100_gamma*z_alpha_gamma...
        +phi100_gamma*z_alpha_gamma+phi010_gamma_gamma*z_beta...
        +phi010_gamma*z_beta_gamma+phi010_gamma*z_beta_gamma...
        +phi001_gamma_gamma*z_gamma)...
        ;
    
    derivative_local(7)=derivative_local(7)+...
        nodal_vals(first_index+1)*phi000_alpha_beta...
        ...
        +nodal_vals(first_index+2)*(...
        phi100_alpha_beta*x_alpha+phi100_alpha*x_alpha_beta...
        +phi010_alpha_beta*x_beta+phi010_beta*x_alpha_beta...
        +phi001_alpha_beta*x_gamma+phi001_alpha*x_beta_gamma...
        +phi001_beta*x_alpha_gamma+phi001*x_alpha_beta_gamma)...
        ...
        +nodal_vals(first_index+3)*(...
        phi100_alpha_beta*y_alpha+phi100_alpha*y_alpha_beta...
        +phi010_alpha_beta*y_beta+phi010_beta*y_alpha_beta...
        +phi001_alpha_beta*y_gamma+phi001_alpha*y_beta_gamma...
        +phi001_beta*y_alpha_gamma+phi001*y_alpha_beta_gamma)...
        ...
        +nodal_vals(first_index+4)*(...
        phi100_alpha_beta*z_alpha+phi100_alpha*z_alpha_beta...
        +phi010_alpha_beta*z_beta+phi010_beta*z_alpha_beta...
        +phi001_alpha_beta*z_gamma+phi001_alpha*z_beta_gamma...
        +phi001_beta*z_alpha_gamma+phi001*z_alpha_beta_gamma)...
        ;
    
    derivative_local(8)=derivative_local(8)+...
        nodal_vals(first_index+1)*phi000_alpha_gamma...
        ...
        +nodal_vals(first_index+2)*(...
        phi100_alpha_gamma*x_alpha+phi100_alpha*x_alpha_gamma...
        +phi010_alpha_gamma*x_beta+phi010_alpha*x_beta_gamma...
        +phi010_gamma*x_alpha_beta+phi010*x_alpha_beta_gamma...
        +phi001_alpha_gamma*x_gamma+phi001_gamma*x_alpha_gamma)...
        ...
        +nodal_vals(first_index+3)*(...
        phi100_alpha_gamma*y_alpha+phi100_alpha*y_alpha_gamma...
        +phi010_alpha_gamma*y_beta+phi010_alpha*y_beta_gamma...
        +phi010_gamma*y_alpha_beta+phi010*y_alpha_beta_gamma...
        +phi001_alpha_gamma*y_gamma+phi001_gamma*y_alpha_gamma)...
        ...
        +nodal_vals(first_index+4)*(...
        phi100_alpha_gamma*z_alpha+phi100_alpha*z_alpha_gamma...
        +phi010_alpha_gamma*z_beta+phi010_alpha*z_beta_gamma...
        +phi010_gamma*z_alpha_beta+phi010*z_alpha_beta_gamma...
        +phi001_alpha_gamma*z_gamma+phi001_gamma*z_alpha_gamma)...
        ;
    
    derivative_local(9)=derivative_local(9)+...
        nodal_vals(first_index+1)*phi000_beta_gamma...
        ...
        +nodal_vals(first_index+2)*(...
        phi100_beta_gamma*x_alpha+phi100_beta*x_alpha_gamma...
        +phi100_gamma*x_alpha_beta+phi100*x_alpha_beta_gamma...
        +phi010_beta_gamma*x_beta+phi010_beta*x_beta_gamma...
        +phi001_beta_gamma*x_gamma+phi001_gamma*x_beta_gamma)...
        ...
        +nodal_vals(first_index+3)*(...
        phi100_beta_gamma*y_alpha+phi100_beta*y_alpha_gamma...
        +phi100_gamma*y_alpha_beta+phi100*y_alpha_beta_gamma...
        +phi010_beta_gamma*y_beta+phi010_beta*y_beta_gamma...
        +phi001_beta_gamma*y_gamma+phi001_gamma*y_beta_gamma)...
        ...
        +nodal_vals(first_index+4)*(...
        phi100_beta_gamma*z_alpha+phi100_beta*z_alpha_gamma...
        +phi100_gamma*z_alpha_beta+phi100*z_alpha_beta_gamma...
        +phi010_beta_gamma*z_beta+phi010_beta*z_beta_gamma...
        +phi001_beta_gamma*z_gamma+phi001_gamma*z_beta_gamma)...
        ;
    
end



J=get_isoparametric_mapping_Jacobian(alpha,beta,gamma,eX,eY,eZ);
x=J\derivative_local;

%-----------
% 
% test=[derivative_local(1:1:3);derivative_local(7:1:9);derivative_local(4:1:6)];
% x=J\test;

%----------------

sol(2:1:7)=x(1:1:6);

end