function sol=local_basis_3d(alpha,beta,gamma,orientations,types,orders)
sol=basis(alpha,orientations(1),types(1),orders(1))...
    *basis(beta,orientations(2),types(2),orders(2))...
    *basis(gamma,orientations(3),types(3),orders(3));
end