function sol=map_to_global_1_compt_3d(alpha,beta,gamma,eCompt,orders)
sol=eCompt(1)*isoBasis(alpha,0,orders(1))*isoBasis(beta,0,orders(2))*isoBasis(gamma,0,orders(3))...
    +eCompt(2)*isoBasis(alpha,1,orders(1))*isoBasis(beta,0,orders(2))*isoBasis(gamma,0,orders(3))...
    +eCompt(3)*isoBasis(alpha,0,orders(1))*isoBasis(beta,1,orders(2))*isoBasis(gamma,0,orders(3))...
    +eCompt(4)*isoBasis(alpha,1,orders(1))*isoBasis(beta,1,orders(2))*isoBasis(gamma,0,orders(3))...
    +eCompt(5)*isoBasis(alpha,0,orders(1))*isoBasis(beta,0,orders(2))*isoBasis(gamma,1,orders(3))...
    +eCompt(6)*isoBasis(alpha,1,orders(1))*isoBasis(beta,0,orders(2))*isoBasis(gamma,1,orders(3))...
    +eCompt(7)*isoBasis(alpha,0,orders(1))*isoBasis(beta,1,orders(2))*isoBasis(gamma,1,orders(3))...
    +eCompt(8)*isoBasis(alpha,1,orders(1))*isoBasis(beta,1,orders(2))*isoBasis(gamma,1,orders(3));
end