WHAT TO DO


FOR TODAY


CHECK TO MAKE SURE THE FOLLOWING FUNCTION HAS NO BUG

create_temperature_gradient_3d

IMPLEMENT TO MAKE FEASIBLE TEMPERATURE GRADIENT WITH DIFFERENT METHODS!

(PARALLEL ALGORITHM WO TERMS, TRADITIONAL, ETC)

CREATE INITIAL CONDITION CO