function movie_creator_2d(nframes_last_sim,frames,ci,T,nex,ney,ci_ave,ci_fluc,include_fluc,diff,...
    counter_init,output_path,video_method,fps,duration,iframe,...
    ifig_raw,frame_pos,frame_size,minz,maxz,...
    figure_analysis,nx,ny,x_coord,y_coord,...
    frequency_domain,limS,...
    xspinodal,yspinodal,xbinodal,ybinodal,...
    alpha,beta,fc,limSstretcher,...
    nx_grad,ny_grad,x_grad,y_grad,contour_lgd_font_size,...
    simulation_folder,...
    view_simulation_only,...
    nworkers)

% function movie_creator_2d(nframes_last_sim,frames,ci,T,nex,ney,ci_ave,ci_fluc,include_fluc,diff,...
%     counter_init,output_path,video_method,fps,duration,iframe,...
%     ifig_raw,frame_pos,frame_size,minz,maxz,...
%     figure_analysis,nx,ny,x_coord,y_coord,...
%     frequency_domain,limS,...
%     xspinodal,yspinodal,xbinodal,ybinodal,...
%     ne,weights,adjusted_diffT,Two_chi_n1,n1,n2,...
%     dxdy,...
%     alpha,beta,fc,limSstretcher,...
%     nx_grad,ny_grad,x_grad,y_grad,contour_lgd_font_size,...
%     simulation_folder,...
%     grad_T,entropy,view_simulation_only)

if view_simulation_only==0
    elapsed=toc(counter_init);
elseif view_simulation_only==1
    elapsed=0;
end
if nframes_last_sim~=0
    fig=figure(ifig_raw);
    set(fig,'Position',[frame_pos(1) frame_pos(2) frame_size(1) frame_size(2)])
    output_conc=[simulation_folder 'concentration/iteration_'];
    output_time=[simulation_folder 'time/iteration_'];
    co=dlmread([output_conc '1']);
    c=co;
    timeo=0;
    time=timeo;
%     dt=inf;
%     [frames(1),~,ac_t,logS,limS]=visual_2d_2018(...
%         figure_analysis,c,nx,ny,x_coord,y_coord,minz,maxz,time,...
%         frequency_domain,ci_ave,limS,0,...
%         xspinodal,yspinodal,xbinodal,ybinodal,T,ci,...
%         1,...
%         [0 0 0],alpha,beta,fc,limSstretcher,...
%         nx_grad,ny_grad,x_grad,y_grad,contour_lgd_font_size,...
%         nworkers);
    
    
    [frames(1),~,ac_t,logS,limS]=visual_2d(...
        figure_analysis,c,nx,ny,x_coord,y_coord,minz,maxz,time,...
        frequency_domain,ci_ave,limS,0,...
        xspinodal,yspinodal,xbinodal,ybinodal,T,ci,...
        1,...
        [0 0 0],alpha,beta,fc,limSstretcher,...
        nx_grad,ny_grad,x_grad,y_grad,contour_lgd_font_size,...
        nworkers);
    
    
    for iVisual=2:1:nframes_last_sim-1
%         co=c;
        c=dlmread([output_conc num2str(iVisual)]);
%         timeo=time;
        time=dlmread([output_time num2str(iVisual)]);
%         dt=time-timeo;
%         [frames(iVisual),~,ac_t,logS,limS]=visual_2d_2018(...
%             figure_analysis,c,nx,ny,x_coord,y_coord,minz,maxz,time,...
%             frequency_domain,ci_ave,limS,logS,...
%             xspinodal,yspinodal,xbinodal,ybinodal,T,ci,...
%             iVisual,...
%             ac_t,...
%             alpha,beta,fc,limSstretcher,...
%             nx_grad,ny_grad,x_grad,y_grad,contour_lgd_font_size,...
%             nworkers);
        
        [frames(iVisual),~,ac_t,logS,limS]=visual_2d(...
            figure_analysis,c,nx,ny,x_coord,y_coord,minz,maxz,time,...
            frequency_domain,ci_ave,limS,logS,...
            xspinodal,yspinodal,xbinodal,ybinodal,T,ci,...
            iVisual,...
            ac_t,alpha,beta,fc,limSstretcher,...
            nx_grad,ny_grad,x_grad,y_grad,contour_lgd_font_size,...
            nworkers);

    end
    close(fig)
    elapsed=elapsed+dlmread([simulation_folder 'specification/elapsed']);
    nRuns=2;
    elapsed_path=[simulation_folder 'specification/elapsed_'];
    while exist([elapsed_path num2str(nRuns)],'file')
        elapsed=elapsed+dlmread([elapsed_path num2str(nRuns)]);
        nRuns=nRuns+1;
    end
end
elapsed=elapsed/60;
visual=frames;
if length(ci)==1 && length(T)==1
    vid_title=sprintf('2D Cahn Hilliard,%dx%d,ci=%1.3f,fluc=%1.4f,diff=%d,T=%0.3f,elapsed time=%1.3fmin.avi',nex,ney,ci_ave,ci_fluc*include_fluc,diff,T,elapsed);
elseif length(ci)==2 && length(T)==1
    vid_title=sprintf('2D Cahn Hilliard,%dx%d,ci=[%1.2f,%1.2f],fluc=%1.4f,diff=%d,T=%0.3f,elapsed time=%1.3fmin.avi',nex,ney,ci(1),ci(2),ci_fluc*include_fluc,diff,T,elapsed);
elseif length(ci)==1 && length(T)==2
    vid_title=sprintf('2D Cahn Hilliard,%dx%d,ci=%1.3f,fluc=%1.4f,diff=%d,T=[%1.2f,%1.2f],elapsed time=%1.3fmin.avi',nex,ney,ci_ave,ci_fluc*include_fluc,diff,T(1),T(2),elapsed);
elseif length(ci)==2 && length(T)==2
    vid_title=sprintf('2D Cahn Hilliard,%dx%d,ci=[%1.2f,%1.2f],fluc=%1.4f,diff=%d,T=[%1.2f,%1.2f],elapsed time=%1.3fmin.avi',nex,ney,ci(1),ci(2),ci_fluc*include_fluc,diff,T(1),T(2),elapsed);
end
if view_simulation_only==1
    mkdir(output_path);
end
vid_title=[output_path vid_title];
video=VideoWriter(vid_title, 'Uncompressed AVI');
fps_corrected=fps_correction(video_method,fps,duration,iframe);
video.FrameRate=fps_corrected;
open(video)
writeVideo(video,visual);
close(video)
fig=figure(ifig_raw);
set(fig,'Position',[frame_pos(1) frame_pos(2) frame_size(1) frame_size(2)])
movie(gcf,visual,1,fps_corrected)
close(fig)
end